# Session 05

## Numpy

In [1]:
import numpy as np

In [2]:
# Python list
numbers_list = [1, 2, 3, 4, 5]
# NumPy array
numbers_array = np.array([1, 2, 3, 4, 5])

In [3]:
# 1 row x 5 columns - vector, 1d
vector = np.array([1, 2, 3, 4, 5])
# vector.ndim = 1 -> axes
# vector.shape = (5,1) -> size in each direction
# vector.size = 5 -> number of values

# 2 rows x 3 columns; matrix - 2d
matrix = np.array([[1, 2, 3],
[4, 5, 6]])
matrix
# matrix.ndim = 2, matrix.shape = (2,3), matrix.size = 6

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Placeholder arrays
np.zeros((2,3)) # all zeros

np.ones((2,3)) # all 1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# special numpy arrays

# NumPy array from 1 until 10 in steps of 2
np.arange(1,10,2)

# NumPy array of 5 random integers between 1 and 10
np.random.seed(1234) # makes the random set repeatable 
random_array = np.random.randint(1,10,5)
random_array2 = np.random.randint(1,10,5)
print(random_array)
print(random_array2)

# NumPy array of 10 repeated 5 times
np.repeat(10,5)

# NumPy array repeated x times
np.tile(vector, 2)

[4 7 6 5 9]
[2 8 7 9 1]

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [21]:
# simulating data

# Create a Generator
rng = np.random.default_rng()

# 10 data points from normal distributed data with a mean of 0, sd 1
rng.normal(0,1,10)
# can also use uniform distribution, poisson etc

array([-0.35164186,  1.06387107, -0.28169781, -0.27477793,  0.71959381,
        0.07747421,  1.08618746,  0.19005109,  0.17528705, -0.85468298])

In [22]:
# reshaping arrays

# 2 rows x 3 columns
matrix = np.array([[1, 2, 3],[4, 5, 6]])

# 3 rows x 2 column
matrix.T # transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# collapse/flatten to 1d

# 2 rows x 3 columns
matrix = np.array([[1, 2, 3],[4, 5, 6]])
# 1 row x 6 columns
matrix.flatten()

In [23]:
# shared axes size, can be stacked together on that axes

matrix1 = np.array([[1, 2, 3],
[4, 5, 6]])
matrix2 = np.array([[7, 8, 9],
[10, 11, 12]])

print(np.vstack((matrix1,matrix2))) #vertical stack
print(np.hstack((matrix1,matrix2))) #horizontal stack

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

In [27]:
# apply operations to all values at once, without a loop

numbers_array = np.array([1, 2, 3, 4, 5])
numbers_array * 2
print(numbers_array)
# array([ 2, 4, 6, 8, 10])

# can perform operations when arrays are same length
matrix1 = np.array([[1, 2, 3],[4, 5, 6]])
matrix2 = np.array([[7, 8, 9],[10, 11, 12]])
matrix_sum = matrix2 - matrix1
print(matrix_sum)

# can summarize values
matrix1 = np.array([[1, 2, 3],[4, 5, 6]])
print(matrix1.sum()) #1 + 2 + 3 + 4 + 5 + 6 = 21
print(matrix1.max()) #6
print(matrix1.mean()) # 1 + 2 + 3 + 4 + 5 + 6 / 6 = 3.5

[1 2 3 4 5]
[[6 6 6]
 [6 6 6]]
21
6
3.5

### Multi-directional operations

In [28]:
matrix1 = np.array([[1, 2, 3],[4, 5, 6]])
matrix1.mean(axis=0)
matrix1.mean(axis=1)

array([2., 5.])

In [30]:
# index and slice arrays like a list
matrix1 = np.array([[1, 2, 3],[4, 5, 6]])
print(matrix1[0,:]) #first row
print(matrix[:,1]) #second column
print(matrix[1,1]) #second row, second column

[1 2 3]
[2 5]
5

In [32]:
# mutate or update elements; also, copy
matrix1 = np.array([[1, 2, 3],[4, 5, 6]])
matrix3 = matrix1.copy()
matrix3[1,1] = 50 #replace 5 with 50, original not changed
print(matrix3)
print(matrix1)

[[ 1  2  3]
 [ 4 50  6]]
[[1 2 3]
 [4 5 6]]

In [34]:
# check if all values share factor
print(matrix3 % 3 == 0)

# can filter with boolean expression as mask
matrix3[matrix3 % 3 == 0]

[[False False  True]
 [False False  True]]

array([3, 6])

In [36]:
# masks to generate new arrays with conditionals
np.where(matrix3 % 3 == 0, # condition
matrix3, # return the element if True
0) # return 0 if False
# array([[ 0, 0, 3], [ 0, 0, 6]])

array([[0, 0, 3],
       [0, 0, 6]])

### Exercises

In [41]:
# exercise 1
# 1d array of numbers 1 to 20
# compute sum, mean, standard dev of array
arr1 = np.arange(1,21,1)

print(arr1)
print(arr1.sum())
print(arr1.mean())
print(arr1.std())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
210
10.5
5.766281297335398

In [45]:
# exercise 2
arr2 = np.array([[2,7,12],[4,15,3],[8,1,20]])

# select all elements > 10
print(
    arr2[arr2 > 10]
)

# replace all elements < 5 with 0
print(np.where(arr2 < 5, 0, arr2))

[12 15 20]
[[ 0  7 12]
 [ 0 15  0]
 [ 8  0 20]]

In [53]:
# exercise 3
arr3 = np.array([[2, 7, 12],
    [4, 15, 3],
    [8, 1, 20]])

# print col 1
print(arr3[:,0])

# print last row
print(arr3[-1:])

# print element in r 2nd, c 3rd
print(arr3[1,2])

[2 4 8]
[[ 8  1 20]]
3

In [58]:
# Exercise 4
arr4 = np.array([[2, 7, 12],
    [4, 15, 3],
    [8, 1, 20]])

# sum of each column
print(arr4.sum(axis=0))

# mean of each row
print(arr4.mean(axis=1))

[14 23 35]
[7.         7.33333333 9.66666667]

## Pandas

- Python library for data analysis and manipulation.
- Works with tabular data (like csv)
- Includes dataframes (2d labeled tables), series (1d labelled array)

In [59]:
import pandas as pd

## Dataframes

In [ ]:
# cols labelled with names
# rows have label or index
# each col is a Series (1d array) with shared type
# can have different types across cols

df = pd.DataFrame({
    "X": [True, False, True, True, False], # bool
    "Y": [3.14, 7.65, 2.56, 7.89, 1.23], # float
    "Z": ["o", "a-", "b+", "b-", "o"] # str
})

In [ ]:
bike_thefts_df = pd.read_csv('./05_src/data/slides_data/bicycle_thefts_4326.csv')
print(bike_thefts_df.shape)
print(bike_thefts_df.dtypes)

   _id  OBJECTID event_unique_id        Primary_Offence      Occurrence_Date  \
0    1     17744  GO-20179016397            THEFT UNDER  2017-10-03T00:00:00
1    2     17759  GO-20172033056  THEFT UNDER - BICYCLE  2017-11-08T00:00:00
2    3     17906  GO-20189030822  THEFT UNDER - BICYCLE  2018-09-14T00:00:00
3    4     17962   GO-2015804467            THEFT UNDER  2015-05-07T00:00:00
4    5     17963  GO-20159002781            THEFT UNDER  2015-05-16T00:00:00

   Occurrence_Year Occurrence_Month Occurrence_DayOfWeek  \
0             2017          October              Tuesday
1             2017         November            Wednesday
2             2018        September               Friday
3             2015              May             Thursday
4             2015              May             Saturday

   Occurrence_DayOfMonth  Occurrence_DayOfYear  ...  Premises_Type  \
0                      3                   276  ...        Outside
1                      8                   312  ...          House
2                     14                   257  ...        Transit
3                      7                   127  ...        Transit
4                     16                   136  ...        Transit

      Bike_Make  Bike_Model Bike_Type Bike_Speed  Bike_Colour  Cost_of_Bike  \
0            GI    ESCAPE 2        OT          7          BLK         700.0
1  UNKNOWN MAKE         NaN        TO          1          BLK        1100.0
2            OT  CROSSTRAIL        MT         24          BLK         904.0
3            GT         NaN        TO         10       BLKDGR         400.0
4            GI         NaN        MT          6          RED         600.0

      Status ObjectId2                                           geometry
0     STOLEN         1  {'type': 'Point', 'coordinates': (-79.50655965...
1  RECOVERED         2  {'type': 'Point', 'coordinates': (-79.50484874...
2     STOLEN         3  {'type': 'Point', 'coordinates': (-79.51170915...
3     STOLEN         4  {'type': 'Point', 'coordinates': (-79.51170915...
4     STOLEN         5  {'type': 'Point', 'coordinates': (-79.51132657...

[5 rows x 33 columns]
         _id  OBJECTID event_unique_id        Primary_Offence  \
25566  25567     11462  GO-20169005434            THEFT UNDER
25567  25568     11695  GO-20161170896            THEFT UNDER
25568  25569     11883  GO-20169007653  THEFT UNDER - BICYCLE

           Occurrence_Date  Occurrence_Year Occurrence_Month  \
25566  2016-06-04T00:00:00             2016             June
25567  2016-07-04T00:00:00             2016             July
25568  2016-07-22T00:00:00             2016             July

      Occurrence_DayOfWeek  Occurrence_DayOfMonth  Occurrence_DayOfYear  ...  \
25566             Saturday                      4                   156  ...
25567               Monday                      4                   186  ...
25568               Friday                     22                   204  ...

       Premises_Type     Bike_Make       Bike_Model Bike_Type Bike_Speed  \
25566      Apartment            SC           ANTRIM        MT         24
25567     Commercial  UNKNOWN MAKE              NaN        SC          1
25568        Outside            SU  ASCENT MOUNTAIN        MT         21

       Bike_Colour  Cost_of_Bike  Status ObjectId2  \
25566          WHI         700.0  STOLEN     25567
25567          NaN        3000.0  STOLEN     25568
25568          ONG         200.0  STOLEN     25569

                                                geometry
25566  {'type': 'Point', 'coordinates': (-79.2360175,...
25567  {'type': 'Point', 'coordinates': (-79.20060719...
25568  {'type': 'Point', 'coordinates': (-79.23734742...

[3 rows x 33 columns]

In [ ]:
print(bike_thefts_df.head()) # defaults to 5 records

   _id  OBJECTID event_unique_id        Primary_Offence      Occurrence_Date  \
0    1     17744  GO-20179016397            THEFT UNDER  2017-10-03T00:00:00
1    2     17759  GO-20172033056  THEFT UNDER - BICYCLE  2017-11-08T00:00:00
2    3     17906  GO-20189030822  THEFT UNDER - BICYCLE  2018-09-14T00:00:00
3    4     17962   GO-2015804467            THEFT UNDER  2015-05-07T00:00:00
4    5     17963  GO-20159002781            THEFT UNDER  2015-05-16T00:00:00

   Occurrence_Year Occurrence_Month Occurrence_DayOfWeek  \
0             2017          October              Tuesday
1             2017         November            Wednesday
2             2018        September               Friday
3             2015              May             Thursday
4             2015              May             Saturday

   Occurrence_DayOfMonth  Occurrence_DayOfYear  ...  Premises_Type  \
0                      3                   276  ...        Outside
1                      8                   312  ...          House
2                     14                   257  ...        Transit
3                      7                   127  ...        Transit
4                     16                   136  ...        Transit

      Bike_Make  Bike_Model Bike_Type Bike_Speed  Bike_Colour  Cost_of_Bike  \
0            GI    ESCAPE 2        OT          7          BLK         700.0
1  UNKNOWN MAKE         NaN        TO          1          BLK        1100.0
2            OT  CROSSTRAIL        MT         24          BLK         904.0
3            GT         NaN        TO         10       BLKDGR         400.0
4            GI         NaN        MT          6          RED         600.0

      Status ObjectId2                                           geometry
0     STOLEN         1  {'type': 'Point', 'coordinates': (-79.50655965...
1  RECOVERED         2  {'type': 'Point', 'coordinates': (-79.50484874...
2     STOLEN         3  {'type': 'Point', 'coordinates': (-79.51170915...
3     STOLEN         4  {'type': 'Point', 'coordinates': (-79.51170915...
4     STOLEN         5  {'type': 'Point', 'coordinates': (-79.51132657...

[5 rows x 33 columns]
         _id  OBJECTID event_unique_id        Primary_Offence  \
25566  25567     11462  GO-20169005434            THEFT UNDER
25567  25568     11695  GO-20161170896            THEFT UNDER
25568  25569     11883  GO-20169007653  THEFT UNDER - BICYCLE

           Occurrence_Date  Occurrence_Year Occurrence_Month  \
25566  2016-06-04T00:00:00             2016             June
25567  2016-07-04T00:00:00             2016             July
25568  2016-07-22T00:00:00             2016             July

      Occurrence_DayOfWeek  Occurrence_DayOfMonth  Occurrence_DayOfYear  ...  \
25566             Saturday                      4                   156  ...
25567               Monday                      4                   186  ...
25568               Friday                     22                   204  ...

       Premises_Type     Bike_Make       Bike_Model Bike_Type Bike_Speed  \
25566      Apartment            SC           ANTRIM        MT         24
25567     Commercial  UNKNOWN MAKE              NaN        SC          1
25568        Outside            SU  ASCENT MOUNTAIN        MT         21

       Bike_Colour  Cost_of_Bike  Status ObjectId2  \
25566          WHI         700.0  STOLEN     25567
25567          NaN        3000.0  STOLEN     25568
25568          ONG         200.0  STOLEN     25569

                                                geometry
25566  {'type': 'Point', 'coordinates': (-79.2360175,...
25567  {'type': 'Point', 'coordinates': (-79.20060719...
25568  {'type': 'Point', 'coordinates': (-79.23734742...

[3 rows x 33 columns]

In [65]:
print(bike_thefts_df.tail(3)) # last 3 items

         _id  OBJECTID event_unique_id        Primary_Offence  \
25566  25567     11462  GO-20169005434            THEFT UNDER
25567  25568     11695  GO-20161170896            THEFT UNDER
25568  25569     11883  GO-20169007653  THEFT UNDER - BICYCLE

           Occurrence_Date  Occurrence_Year Occurrence_Month  \
25566  2016-06-04T00:00:00             2016             June
25567  2016-07-04T00:00:00             2016             July
25568  2016-07-22T00:00:00             2016             July

      Occurrence_DayOfWeek  Occurrence_DayOfMonth  Occurrence_DayOfYear  ...  \
25566             Saturday                      4                   156  ...
25567               Monday                      4                   186  ...
25568               Friday                     22                   204  ...

       Premises_Type     Bike_Make       Bike_Model Bike_Type Bike_Speed  \
25566      Apartment            SC           ANTRIM        MT         24
25567     Commercial  UNKNOWN MAKE              NaN        SC          1
25568        Outside            SU  ASCENT MOUNTAIN        MT         21

       Bike_Colour  Cost_of_Bike  Status ObjectId2  \
25566          WHI         700.0  STOLEN     25567
25567          NaN        3000.0  STOLEN     25568
25568          ONG         200.0  STOLEN     25569

                                                geometry
25566  {'type': 'Point', 'coordinates': (-79.2360175,...
25567  {'type': 'Point', 'coordinates': (-79.20060719...
25568  {'type': 'Point', 'coordinates': (-79.23734742...

[3 rows x 33 columns]

In [ ]:
# Renaming columns

bike_thefts_df = bike_thefts_df.rename(columns = {"cost_of_bike": "bike_cost" })

In [ ]:
# Profiling columns
# focus on subset of data; can get single column by name like a key
df = bike_thefts_df
df["Status"].unique()
# Output
# array(['STOLEN', 'RECOVERED', 'UNKNOWN'], dtype=object)

# count occurrences
df["Status"].value_counts()

Status
STOLEN       24807
UNKNOWN        454
RECOVERED      308
Name: count, dtype: int64

In [68]:
# get overview of dataframe; shape, size (rows and cols), keys and datatype, count of non-nulls in each col
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25569 entries, 0 to 25568
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   _id                    25569 non-null  int64
 1   OBJECTID               25569 non-null  int64
 2   event_unique_id        25569 non-null  str
 3   Primary_Offence        25569 non-null  str
 4   Occurrence_Date        25569 non-null  str
 5   Occurrence_Year        25569 non-null  int64
 6   Occurrence_Month       25569 non-null  str
 7   Occurrence_DayOfWeek   25569 non-null  str
 8   Occurrence_DayOfMonth  25569 non-null  int64
 9   Occurrence_DayOfYear   25569 non-null  int64
 10  Occurrence_Hour        25569 non-null  int64
 11  Report_Date            25569 non-null  str
 12  Report_Year            25569 non-null  int64
 13  Report_Month           25569 non-null  str
 14  Report_DayOfWeek       25569 non-null  str
 15  Report_DayOfMonth      25569 non-null  int64
 16  Report_DayOfYear       25569 non-null  int64
 17  Report_Hour            25569 non-null  int64
 18  Division               25569 non-null  str
 19  City                   25569 non-null  str
 20  Hood_ID                25569 non-null  str
 21  NeighbourhoodName      25569 non-null  str
 22  Location_Type          25569 non-null  str
 23  Premises_Type          25569 non-null  str
 24  Bike_Make              25448 non-null  str
 25  Bike_Model             15923 non-null  str
 26  Bike_Type              25569 non-null  str
 27  Bike_Speed             25569 non-null  int64
 28  Bike_Colour            23508 non-null  str
 29  Cost_of_Bike           23825 non-null  float64
 30  Status                 25569 non-null  str
 31  ObjectId2              25569 non-null  int64
 32  geometry               25569 non-null  str
dtypes: float64(1), int64(12), str(20)
memory usage: 6.4 MB

## Changing datatypes

In [69]:
# Convert occurrence date columns to datetime
df["Occurrence_Date"] = pd.to_datetime(df["Occurrence_Date"])

# Convert Status columns to category
df["Status"] = df["Status"].astype("category")

## Describing and editing dataframe

In [70]:
df.describe(include = "all") # by default, numeric cols only; use include="all" to get all cols

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
count,25569.000000,25569.000000,25569,25569,25569,25569.000000,25569,25569,25569.000000,25569.000000,...,25569,25448,15923,25569,25569.000000,23508,23825.000000,25569,25569.000000,25569
unique,NaN,NaN,22771,66,NaN,NaN,12,7,NaN,NaN,...,7,820,8097,13,NaN,252,NaN,3,NaN,5816
top,NaN,NaN,GO-20201550944,THEFT UNDER,NaN,NaN,July,Friday,NaN,NaN,...,Outside,OT,UNKNOWN,MT,NaN,BLK,NaN,STOLEN,NaN,"{'type': 'Point', 'coordinates': (-79.38372586..."
freq,NaN,NaN,14,11904,NaN,NaN,4002,3924,NaN,NaN,...,7960,4991,304,8245,NaN,7422,NaN,24807,NaN,167
mean,12785.000000,12909.173218,NaN,NaN,2017-09-04 03:39:28.321013,2017.124174,NaN,NaN,15.616684,202.227698,...,NaN,NaN,NaN,NaN,14.164144,NaN,949.542371,NaN,12785.000000,NaN
min,1.000000,1.000000,NaN,NaN,2009-09-01 00:00:00,2009.000000,NaN,NaN,1.000000,1.000000,...,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,NaN,1.000000,NaN
25%,6393.000000,6456.000000,NaN,NaN,2016-01-06 00:00:00,2016.000000,NaN,NaN,8.000000,153.000000,...,NaN,NaN,NaN,NaN,6.000000,NaN,350.000000,NaN,6393.000000,NaN
50%,12785.000000,12918.000000,NaN,NaN,2017-09-05 00:00:00,2017.000000,NaN,NaN,16.000000,205.000000,...,NaN,NaN,NaN,NaN,15.000000,NaN,600.000000,NaN,12785.000000,NaN
75%,19177.000000,19360.000000,NaN,NaN,2019-06-20 00:00:00,2019.000000,NaN,NaN,23.000000,259.000000,...,NaN,NaN,NaN,NaN,21.000000,NaN,1000.000000,NaN,19177.000000,NaN
max,25569.000000,25806.000000,NaN,NaN,2020-12-30 00:00:00,2020.000000,NaN,NaN,31.000000,366.000000,...,NaN,NaN,NaN,NaN,99.000000,NaN,120000.000000,NaN,25569.000000,NaN
std,7381.278853,7448.318562,NaN,NaN,NaN,1.960127,NaN,NaN,8.592886,76.821431,...,NaN,NaN,NaN,NaN,10.559215,NaN,1675.880345,NaN,7381.278853,NaN

In [71]:
# drop cols; won't affect original dataframe unless re-assigned
df.drop(columns = "_id")

# add new col with repeated data
df["current_year"] = 2026

# add col with parts of existing col
df["Occurrence_Month"] = df["Occurrence_Month"].str[:3]

## Filter and select

In [73]:
# loc access rows based on bool
df.loc[df["Bike_Model"].isna()]

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry,current_year
1,2,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08,2017,Nov,Wednesday,8,312,...,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874...",2026
3,4,17962,GO-2015804467,THEFT UNDER,2015-05-07,2015,May,Thursday,7,127,...,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
4,5,17963,GO-20159002781,THEFT UNDER,2015-05-16,2015,May,Saturday,16,136,...,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657...",2026
7,8,20993,GO-2019819460,THEFT UNDER,2019-05-01,2019,May,Wednesday,1,121,...,GARY FISHER,NaN,OT,7,BLK,800.0,STOLEN,8,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
8,9,21209,GO-20179014159,THEFT UNDER,2017-09-06,2017,Sep,Wednesday,6,249,...,UK,NaN,RG,20,BLK,700.0,STOLEN,9,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25561,25562,9046,GO-20149007555,THEFT UNDER,2014-10-03,2014,Oct,Friday,3,276,...,UK,NaN,RG,30,WHI,300.0,STOLEN,25562,"{'type': 'Point', 'coordinates': (-79.23001795...",2026
25562,25563,9083,GO-20143134832,THEFT UNDER,2014-10-17,2014,Oct,Friday,17,290,...,SUPERCYCLE,NaN,OT,10,YEL,NaN,STOLEN,25563,"{'type': 'Point', 'coordinates': (-79.21116678...",2026
25563,25564,9155,GO-20143239833,THEFT UNDER,2014-11-04,2014,Nov,Tuesday,4,308,...,CHEROKEE,NaN,MT,21,BLU,100.0,STOLEN,25564,"{'type': 'Point', 'coordinates': (-79.23033103...",2026
25565,25566,11318,GO-20169004589,THEFT UNDER,2016-05-16,2016,May,Monday,16,137,...,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046...",2026
25567,25568,11695,GO-20161170896,THEFT UNDER,2016-07-04,2016,Jul,Monday,4,186,...,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719...",2026

In [ ]:
# access rows of data where line is NA; query() is easier to read the code, but is slower than loc()
df.query("Bike_Model.isna()")

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry,current_year
1,2,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08,2017,Nov,Wednesday,8,312,...,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874...",2026
3,4,17962,GO-2015804467,THEFT UNDER,2015-05-07,2015,May,Thursday,7,127,...,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
4,5,17963,GO-20159002781,THEFT UNDER,2015-05-16,2015,May,Saturday,16,136,...,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657...",2026
7,8,20993,GO-2019819460,THEFT UNDER,2019-05-01,2019,May,Wednesday,1,121,...,GARY FISHER,NaN,OT,7,BLK,800.0,STOLEN,8,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
8,9,21209,GO-20179014159,THEFT UNDER,2017-09-06,2017,Sep,Wednesday,6,249,...,UK,NaN,RG,20,BLK,700.0,STOLEN,9,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25561,25562,9046,GO-20149007555,THEFT UNDER,2014-10-03,2014,Oct,Friday,3,276,...,UK,NaN,RG,30,WHI,300.0,STOLEN,25562,"{'type': 'Point', 'coordinates': (-79.23001795...",2026
25562,25563,9083,GO-20143134832,THEFT UNDER,2014-10-17,2014,Oct,Friday,17,290,...,SUPERCYCLE,NaN,OT,10,YEL,NaN,STOLEN,25563,"{'type': 'Point', 'coordinates': (-79.21116678...",2026
25563,25564,9155,GO-20143239833,THEFT UNDER,2014-11-04,2014,Nov,Tuesday,4,308,...,CHEROKEE,NaN,MT,21,BLU,100.0,STOLEN,25564,"{'type': 'Point', 'coordinates': (-79.23033103...",2026
25565,25566,11318,GO-20169004589,THEFT UNDER,2016-05-16,2016,May,Monday,16,137,...,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046...",2026
25567,25568,11695,GO-20161170896,THEFT UNDER,2016-07-04,2016,Jul,Monday,4,186,...,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719...",2026

In [ ]:
# Filtering

Models_to_keep = ["HYBRID","SIRRUS","ESCAPE"]
# Filter using .loc[]
df.loc[df["Bike_Model"].isin(Models_to_keep)]

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry,current_year
87,88,21080,GO-20191970007,B&E,2019-10-11,2019,Oct,Friday,11,284,...,SPECIALIZED,SIRRUS,TO,21,BLKBLU,950.0,STOLEN,87,"{'type': 'Point', 'coordinates': (-79.48640535...",2026
228,229,1135,GO-20179012278,THEFT UNDER - BICYCLE,2017-08-05,2017,Aug,Saturday,5,217,...,TR,HYBRID,OT,8,BLK,2000.0,STOLEN,224,"{'type': 'Point', 'coordinates': (-79.48678673...",2026
257,258,2748,GO-20189021105,THEFT UNDER - BICYCLE,2018-07-02,2018,Jul,Monday,2,183,...,OT,HYBRID,MT,15,WHI,1800.0,STOLEN,253,"{'type': 'Point', 'coordinates': (-79.48323001...",2026
730,731,17860,GO-20189023474,THEFT UNDER - BICYCLE,2018-07-20,2018,Jul,Friday,20,201,...,GI,ESCAPE,OT,65,GRY,650.0,STOLEN,723,"{'type': 'Point', 'coordinates': (-79.48760733...",2026
899,900,21345,GO-20181755711,B&E,2018-09-21,2018,Sep,Friday,21,264,...,SPECIALIZED,SIRRUS,OT,0,BLU,500.0,STOLEN,890,"{'type': 'Point', 'coordinates': (-79.53250412...",2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24346,24347,21564,GO-20201306023,THEFT UNDER - BICYCLE,2020-05-01,2020,May,Friday,1,122,...,SPECIALIZED,SIRRUS,RG,24,BLK,1300.0,STOLEN,24334,"{'type': 'Point', 'coordinates': (-79.41826195...",2026
24733,24734,1718,GO-20171919540,THEFT UNDER - BICYCLE,2017-10-17,2017,Oct,Tuesday,17,290,...,UNKNOWN MAKE,HYBRID,TO,10,BLK,700.0,UNKNOWN,24721,"{'type': 'Point', 'coordinates': (-79.23103567...",2026
24916,24917,4856,GO-20199023501,THEFT UNDER,2019-07-22,2019,Jul,Monday,22,203,...,GI,ESCAPE,OT,21,BLK,400.0,STOLEN,24904,"{'type': 'Point', 'coordinates': (-79.2826472,...",2026
24998,24999,9803,GO-20159003602,THEFT UNDER,2015-06-14,2015,Jun,Sunday,14,165,...,OT,SIRRUS,MT,18,BLK,800.0,STOLEN,24988,"{'type': 'Point', 'coordinates': (-79.26689373...",2026
25014,25015,6793,GO-20201407793,THEFT UNDER - BICYCLE,2020-06-11,2020,Jun,Thursday,11,163,...,GIANT,ESCAPE,TO,18,GRY,600.0,STOLEN,25004,"{'type': 'Point', 'coordinates': (-79.21309175...",2026

In [ ]:
# large scale data edit

#This makes all the upper case A’s lowercase
df["Bike_Model"] = (df["Bike_Model"].str.replace("A", "a"))

## Grouping

In [76]:
# core workflow in pandas is split-apply-combine; group, apply func to group, combine result into a data structure

#Let’s first group the data by bike model
Model_Groups = df.groupby("Bike_Model")

#Identify unique manufacturers for each group
Model_Groups["Bike_Make"].unique()

# write dataframe to file
df.to_csv("updated_df.csv")

## Exercise

In [ ]:
# Read the CSV file subway_stations.csv into a DataFrame called df.
df = pd.read_csv("./05_src/data/slides_data/subway_stations.csv")

# Display the first 5 rows of the DataFrame.
print(df.head())

# Display the last 2 rows of the DataFrame.
print(df.tail(2))

# Check the number of rows and columns in the DataFrame.
df.shape

# Filter the DataFrame to show only rows where station is "COLLEGE STATION " or "ROYAL YORK STATION".
stations = ["COLLEGE STATION", "ROYAL YORK STATION"]
filtered_df = df.query(f"station.isin({stations})")

# Export the filtered DataFrame to a CSV file called exported_data.csv.
filtered_df.to_csv("exported_data.csv")

     stop_lat   stop_lon             station
0   43.666061 -79.411065    BATHURST STATION
1   43.670149 -79.390089         BAY STATION
2   43.766872 -79.386703     BAYVIEW STATION
3   43.769202 -79.376312   BESSARION STATION
4   43.670049 -79.385389       BLOOR STATION
..        ...        ...                 ...
72  43.734475 -79.450920      WILSON STATION
73  43.686440 -79.312471    WOODBINE STATION
74  43.670997 -79.385956       YONGE STATION
75  43.745172 -79.405930  YORK MILLS STATION
76  43.725248 -79.447692    YORKDALE STATION

[77 rows x 3 columns]
    stop_lat   stop_lon            station
0  43.666061 -79.411065   BATHURST STATION
1  43.670149 -79.390089        BAY STATION
2  43.766872 -79.386703    BAYVIEW STATION
3  43.769202 -79.376312  BESSARION STATION
4  43.670049 -79.385389      BLOOR STATION
     stop_lat   stop_lon             station
75  43.745172 -79.405930  YORK MILLS STATION
76  43.725248 -79.447692    YORKDALE STATION